title: مؤسسة بن سالم للمقاولات العامة
email: Support@binsalim-sa.com
description: >
  تأجير المولدات الكهربائية والمعدات الثقيلة لدعم المشاريع والورش والمواقع داخل المملكة العربية السعودية.

remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme

locale: ar-SA
direction: rtl
logo: /assets/images/logo.png

# ❌ إيقاف المدونة
collections:
  posts:
    output: false

# ❌ إخفاء عناصر المدونة من الهيدر
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false
      share: false
      related: false
      search: false
      minimal_mistakes_skin: "default"

defaults:
  - scope:
      path: ""
    values:
      layout: single

# إجبار استخدام ملف الملاحة
navigation:
  main:
    - title: "الرئيسية"
      url: /
    - title: "الخدمات"
      url: /services/
    - title: "من نحن"
      url: /about/
    - title: "تواصل معنا"
      url: /contact/



